import { StyleSheet } from "react-native";
export const style = StyleSheet.create({
  cartCard: {
    borderWidth: 1,
    borderColor: "#d6d4d4",
    borderRadius: 8,
    backgroundColor: "white",
    marginVertical: "2%",
    padding: "1.5%",
    marginRight: "2%",
  },
  cartView: {
    flexDirection: "row",
  },

  cartTxt: {
    flex: 1,
    fontWeight: "400",
  },
  cartIcon: { flex: 1 },
  cartBtnView: {
    backgroundColor: "#d90404",
    padding: "2%",
    borderRadius: 8,
    margin: "2%",
  },
  cartBtnTxt: {
    color: "white",
    textAlign: "center",
    fontWeight: "500",
  },
  headerDetailsView: {
    flexDirection: "row",
    paddingVertical: "2%",
    backgroundColor: "#dedfe0",
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "black",
    marginVertical: "2%",
  },
  headerDetailsTxt: {
    flex: 1.8,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "500",
  },
  headerDetailsIcon: {
    flex: 0.2,
    alignItems: "center",
  },
  optionView: {
    flexDirection: "row",
    backgroundColor: "white",
    marginVertical: "1%",
    paddingVertical: "2%",
    justifyContent: "center",
  },
  optionTxt: {
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "500",
    borderWidth: 0.8,
    borderColor: "white",
    padding: "1%",
    borderTopLeftRadius: 2,
    paddingHorizontal: "4%",
    backgroundColor: "black",
    color: "white",
  },
  optionTxtActive: {
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "500",
    borderWidth: 0.8,
    borderColor: "black",
    padding: "1%",
    borderTopLeftRadius: 2,
    paddingHorizontal: "4%",
    backgroundColor: "white",
    height: "120%",
  },
  formView: {
    marginHorizontal: "3%",
    marginVertical: "1%",
    padding: "1%",
    borderWidth: 1,
    borderColor: "#d6d4d4",
    borderRadius: 8,
    backgroundColor: "white",
    paddingHorizontal: "4%",
    paddingVertical: "4%",
  },
  headerView: {
    flexDirection: "row",
  },
  headerTxt: {
    flex: 1.8,
    fontWeight: "500",
    fontSize: 16,
  },
  headerIcon: {
    flex: 0.2,
  },
  cardView: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: "#d6d4d4",
    borderBottomColor: "#d6d4d4",
    paddingTop: "2%",
    paddingBottom: "2%",
    borderRadius: 6,
    backgroundColor: "white",
    padding: "2%",
  },
  qrText: {
    textAlign: "center",
    fontWeight: "500",
    fontSize: 20,
  },
  qrIcon: {
    textAlign: "center",
  },
  acvView: {
    flexDirection: "row",
    marginVertical: "1%",
  },
  avcText: {
    flex: 0.8,
    fontWeight: "500",
    textAlignVertical: "center",
  },
  acvIcon: {
    flex: 1.2,
  },
  acvTxtInput: {
    flex: 1.2,
    borderWidth: 1,
    borderColor: "#d6d4d4",
    borderRadius: 8,
    paddingHorizontal: "2%",
  },
  labelText: {
    fontSize: 15,
    fontWeight: "500",
  },
  inputTxt: {
    borderWidth: 1,
    borderColor: "#d6d4d4",
    borderRadius: 8,
    marginVertical: "2%",
    padding: "3%",
  },
  btn: {
    backgroundColor: "black",
    padding: "2%",
    borderRadius: 8,
    marginVertical: "2%",
    marginHorizontal: "4%",
  },
  btnText: {
    textAlign: "center",
    color: "white",
    fontWeight: "500",
  },
  cameraIcon: {
    marginVertical: "2%",
  },
  addBtnView: {
    flexDirection: "row",
    padding: "2%",
    alignSelf: "flex-end",
    width: "50%",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "black",
    backgroundColor: "#5c5c5c",
  },
  addBtnIcon: {
    flex: 0.2,
    color: "white",
  },
  addBtnTxt: {
    flex: 0.8,
    textAlignVertical: "center",
    textAlign: "center",
    color: "white",
    fontWeight: "500",
  },
});
